version: '3.8'
services:
  jupyter-pytorch:
    build: .
    volumes:
      - .:/workspace
    ports:
      - 8888:8888
      - 8080:8080
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    shm_size: '12gb'
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
